const defaultConfig={appearance:{title:'新艾利都 / 剧情档案',intro:'Hooxi 的绝区零剧情视频整合站。沿着代理人的记录，重新进入每一段被以太侵蚀的故事。',bgUrl:'',bgOpacity:18,particles:true,gridEffect:true},cards:[{category:'主线剧情',no:'01',tag:'主线 · 序章',title:'绳匠的序章',desc:'从录像店出发，代理人第一次接触空洞。',video:''},{category:'主线剧情',no:'02',tag:'主线 · 第一章',title:'猫的失物',desc:'在六分街与空洞之间，寻找失踪的委托人。',video:''},{category:'角色剧情分支',no:'03',tag:'角色分支 · 安比',title:'安比的午后',desc:'一份汉堡，一次意外的约会。',video:''},{category:'角色专属 EP / PV',no:'04',tag:'EP / PV · 角色展示',title:'代理人的信号',desc:'收录角色 EP、PV 与战斗演示视频。',video:''},{category:'主题活动',no:'05',tag:'主题活动 · 新艾利都',title:'城市的回声',desc:'记录限时活动与特别主题剧情。',video:''}],tracks:[{name:'示例音乐（替换地址）',url:''}]};
function loadConfig(){try{return JSON.parse(localStorage.getItem('hooxiZZZConfig'))||structuredClone(defaultConfig)}catch{return structuredClone(defaultConfig)}}
let config=loadConfig();let currentTrack=0;const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addMotion(target){if(!target||target.dataset.motionBound)return;target.dataset.motionBound='1';target.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=target.getBoundingClientRect();const x=(e.clientX-r.left)/r.width;const y=(e.clientY-r.top)/r.height;target.style.setProperty('--tilt-x',`${(x-.5)*4}deg`);target.style.setProperty('--tilt-y',`${(.5-y)*4}deg`);target.style.setProperty('--glow-x',`${x*100}%`);target.style.setProperty('--glow-y',`${y*100}%`)});target.addEventListener('pointerleave',()=>{target.style.removeProperty('--tilt-x');target.style.removeProperty('--tilt-y')})}function bindMotion(){document.querySelectorAll('.episode,.page-card,.button,.icon-button,.player-control,.playlist-button,.play-button').forEach(addMotion)}
function save(){localStorage.setItem('hooxiZZZConfig',JSON.stringify(config));toast('配置已保存到本机浏览器')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function applyAppearance(){const a=config.appearance;const [first,...rest]=a.title.split(' / ');$('#heroTitle').innerHTML=`${esc(first)}<br/><span>${esc(rest.join(' / ')||'剧情档案')}</span>`;$('#heroIntro').textContent=a.intro;document.body.style.setProperty('--user-bg',a.bgUrl?`url("${a.bgUrl.replaceAll('"','')}" )`:'none');document.body.style.setProperty('--bg-opacity',a.bgOpacity/100);$('.ambient').classList.toggle('paused',!a.particles);document.body.classList.toggle('no-grid',!a.gridEffect);$('#editTitle').value=a.title;$('#editIntro').value=a.intro;$('#bgUrl').value=a.bgUrl;$('#bgOpacity').value=a.bgOpacity;$('#bgOpacityValue').textContent=`${a.bgOpacity}%`;$('#particles').checked=a.particles;$('#gridEffect').checked=a.gridEffect}
function render(){const grouped={};config.cards.forEach(c=>(grouped[c.category]??=[]).push(c));$('#timeline').innerHTML=Object.entries(grouped).map(([category,items],i)=>`<article class="chapter" data-index="${i}"><div class="chapter-head" role="button" tabindex="0" aria-expanded="true"><span class="chapter-no">${String(i+1).padStart(2,'0')}</span><span class="chapter-title">${esc(category)}</span><span class="chapter-arrow">⌄</span></div><div class="chapter-track">${items.map(ep=>`<div class="episode"><span class="episode-tag">${esc(ep.tag)}</span><h3>${esc(ep.title)}</h3><p>${esc(ep.desc)}</p>${ep.video?`<a class="video-link" href="${esc(ep.video)}" target="_blank" rel="noreferrer">▶ 播放视频 ↗</a>`:'<span class="video-link disabled">◌ 视频待接入</span>'}</div>`).join('')}</div></article>`).join('');document.querySelectorAll('.chapter-head').forEach(h=>{const toggle=()=>{const c=h.parentElement;const open=!c.classList.toggle('closed');h.setAttribute('aria-expanded',open)};h.onclick=toggle;h.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}});renderContentEditor()}
function renderContentEditor(){$('#contentList').innerHTML=config.cards.map((c,i)=>`<div class="content-row"><b>${i+1}</b><input data-i="${i}" data-k="category" value="${esc(c.category)}" placeholder="分类"/><input data-i="${i}" data-k="tag" value="${esc(c.tag)}" placeholder="标签"/><input data-i="${i}" data-k="title" value="${esc(c.title)}" placeholder="标题"/><input data-i="${i}" data-k="desc" value="${esc(c.desc)}" placeholder="简介"/><input data-i="${i}" data-k="video" value="${esc(c.video)}" placeholder="视频链接（可选）"/><button data-remove="${i}" aria-label="删除">×</button></div>`).join('');document.querySelectorAll('#contentList input').forEach(x=>x.oninput=()=>config.cards[x.dataset.i][x.dataset.k]=x.value);document.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{config.cards.splice(+x.dataset.remove,1);renderContentEditor()})}
function renderMusicEditor(){$('#musicList').innerHTML=config.tracks.map((t,i)=>`<div class="music-row"><input data-i="${i}" data-k="name" value="${esc(t.name)}" placeholder="歌曲名称"/><input data-i="${i}" data-k="url" value="${esc(t.url)}" placeholder="音频 URL"/><button data-track-remove="${i}">×</button></div>`).join('');document.querySelectorAll('#musicList input').forEach(x=>x.oninput=()=>config.tracks[x.dataset.i][x.dataset.k]=x.value);document.querySelectorAll('[data-track-remove]').forEach(x=>x.onclick=()=>{config.tracks.splice(+x.dataset.trackRemove,1);renderMusicEditor()})}
function updatePlayer(){const t=config.tracks[currentTrack];$('#trackName').textContent=t?.name||'未选择音乐';$('#audio').src=t?.url||'';$('#playlistItems').innerHTML=config.tracks.map((x,i)=>`<button class="playlist-item ${i===currentTrack?'selected':''}" data-play="${i}">${i+1}. ${esc(x.name)}</button>`).join('');document.querySelectorAll('[data-play]').forEach(x=>x.onclick=()=>{currentTrack=+x.dataset.play;updatePlayer();play()})}
function play(){if(!$('#audio').src){toast('请先在编辑器中添加已授权的音频地址');return}$('#audio').play().then(()=>$('#musicToggle').textContent='❚❚').catch(()=>toast('浏览器阻止了自动播放，请点击播放按钮'))}function next(dir=1){if(!config.tracks.length)return;currentTrack=(currentTrack+dir+config.tracks.length)%config.tracks.length;updatePlayer();play()}
if(document.querySelector('#heroTitle')){applyAppearance();render();}updatePlayer();bindMotion();
if(document.querySelector('#expandAll')){$('#expandAll').onclick=()=>document.querySelectorAll('.chapter').forEach(c=>{c.classList.remove('closed');c.querySelector('.chapter-head').setAttribute('aria-expanded','true')});$('#collapseAll').onclick=()=>document.querySelectorAll('.chapter').forEach(c=>{c.classList.add('closed');c.querySelector('.chapter-head').setAttribute('aria-expanded','false')})}
if(document.querySelector('#editor')){$('#editorOpen').onclick=()=>$('#editor').classList.add('open');$('#editorClose').onclick=()=>$('#editor').classList.remove('open');document.querySelectorAll('.editor-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.editor-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.editor-body').forEach(x=>x.classList.add('hidden'));$(`#${b.dataset.tab}Tab`).classList.remove('hidden');if(b.dataset.tab==='music')renderMusicEditor()});
$('#bgOpacity').oninput=e=>$('#bgOpacityValue').textContent=`${e.target.value}%`;$('#saveAppearance').onclick=()=>{config.appearance={title:$('#editTitle').value,intro:$('#editIntro').value,bgUrl:$('#bgUrl').value,bgOpacity:+$('#bgOpacity').value,particles:$('#particles').checked,gridEffect:$('#gridEffect').checked};applyAppearance();save()};$('#addCard').onclick=()=>{config.cards.push({category:'角色剧情分支',no:'',tag:'新节点',title:'未命名剧情',desc:'填写这段剧情的简介。',video:''});renderContentEditor()};$('#saveContent').onclick=()=>{render();save()};$('#addTrack').onclick=()=>{config.tracks.push({name:'新歌曲',url:''});renderMusicEditor()};$('#saveMusic').onclick=()=>{currentTrack=0;updatePlayer();save()};}
$('#musicToggle').onclick=()=>$('#audio').paused?play():($('#audio').pause(),$('#musicToggle').textContent='▶');$('#prevTrack').onclick=()=>next(-1);$('#nextTrack').onclick=()=>next();$('#volume').oninput=e=>$('#audio').volume=e.target.value;$('#audio').onended=()=>next();$('#playlistOpen').onclick=()=>$('#playlist').classList.toggle('hidden');
if(document.querySelector('#editor')){$('#exportConfig').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}));a.download='hooxi-zzz-config.json';a.click();URL.revokeObjectURL(a.href)};$('#importConfig').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{config=JSON.parse(r.result);applyAppearance();render();updatePlayer();save();toast('配置导入成功')}catch{toast('配置文件格式不正确')}};r.readAsText(file)};$('#resetConfig').onclick=()=>{if(confirm('确定恢复默认内容吗？')){config=structuredClone(defaultConfig);localStorage.removeItem('hooxiZZZConfig');applyAppearance();render();updatePlayer();toast('已恢复默认配置')}};$('#audioUpload').onchange=e=>{[...e.target.files].forEach(file=>{const url=URL.createObjectURL(file);config.tracks.push({name:file.name,url,local:true});});renderMusicEditor();toast('已加入本机歌单，可立即试听')};$('#exportPlaylist').onclick=()=>{const playlist=config.tracks.filter(t=>!t.local).map(t=>({name:t.name,url:t.url}));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(playlist,null,2)],{type:'application/json'}));a.download='playlist.json';a.click();toast('已生成 playlist.json；音频文件请复制到 assets/audio/')};}
window.addEventListener('load',()=>{if(config.tracks[0]?.url)$('#audio').play().catch(()=>toast('点击底部播放器启用音乐'))});
