'use strict';
const http=require('http'),crypto=require('crypto');
const gh=require('./lib/github');
const {createSession,readSession,parseCookies,buildSetCookie}=require('./lib/session');
const {GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET,GITHUB_CALLBACK_URL,GITHUB_REPO_OWNER,GITHUB_REPO_NAME,GITHUB_BRANCH='main',SESSION_SECRET,COOKIE_NAME='hooxi_session',PORT='3001',CORS_ORIGINS='',NODE_ENV='development',OAUTH_SCOPE='public_repo read:user'}=process.env;
const allowedFiles=new Set(['data.js','layout-data.js']),origins=new Set(CORS_ORIGINS.split(',').map(x=>x.trim()).filter(Boolean)),states=new Map(),sessions=new Map(),prod=NODE_ENV==='production';
const cookieOpts={httpOnly:true,secure:prod,sameSite:prod?'None':'Lax',path:'/',maxAge:604800};
function json(res,status,body){const p=JSON.stringify(body);res.writeHead(status,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(p)});res.end(p)}
function cors(req,res){const o=req.headers.origin||'';if(origins.has(o)){res.setHeader('Access-Control-Allow-Origin',o);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Methods','GET,PUT,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Vary','Origin')}}
function session(req){const signed=readSession(parseCookies(req)[COOKIE_NAME],SESSION_SECRET);return signed&&sessions.get(signed.sid)}
function validFile(file){return allowedFiles.has(file)}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>2_000_000)throw Object.assign(new Error('body_too_large'),{status:413})}return JSON.parse(s)}
async function router(req,res){cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const u=new URL(req.url,'http://localhost'),p=u.pathname;try{
if(req.method==='GET'&&p==='/health')return json(res,200,{ok:true});
if(req.method==='GET'&&p==='/api/auth/github/start'){const state=crypto.randomBytes(24).toString('hex');states.set(state,Date.now()+600000);res.writeHead(302,{Location:gh.buildAuthUrl(GITHUB_CLIENT_ID,state,GITHUB_CALLBACK_URL,OAUTH_SCOPE)});return res.end()}
if(req.method==='GET'&&p==='/api/auth/github/callback'){const code=u.searchParams.get('code'),state=u.searchParams.get('state'),exp=states.get(state);states.delete(state);if(!code||!exp||exp<Date.now())return json(res,400,{error:'invalid_state'});const token=(await gh.exchangeCode(GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET,code,GITHUB_CALLBACK_URL)).access_token,user=await gh.getUser(token),permission=await gh.getCollaboratorPermission(token,GITHUB_REPO_OWNER,GITHUB_REPO_NAME,user.login),sid=crypto.randomBytes(32).toString('hex');sessions.set(sid,{token,login:user.login,name:user.name||user.login,avatar:user.avatar_url,permission,canEdit:gh.canEdit(permission),expires:Date.now()+604800000});res.setHeader('Set-Cookie',buildSetCookie(COOKIE_NAME,createSession({sid},SESSION_SECRET),cookieOpts));res.writeHead(302,{Location:[...origins][0]||'/'});return res.end()}
if(req.method==='GET'&&p==='/api/auth/session'){const s=session(req);return s?json(res,200,{authenticated:true,login:s.login,name:s.name,avatar:s.avatar,permission:s.permission,canEdit:s.canEdit}):json(res,401,{authenticated:false})}
if((req.method==='POST'||req.method==='GET')&&p==='/api/auth/logout'){const signed=readSession(parseCookies(req)[COOKIE_NAME],SESSION_SECRET);if(signed)sessions.delete(signed.sid);res.setHeader('Set-Cookie',buildSetCookie(COOKIE_NAME,'',{...cookieOpts,maxAge:0}));return json(res,200,{ok:true})}
if(p==='/api/archive'){const s=session(req);if(!s)return json(res,401,{error:'unauthenticated'});if(!s.canEdit)return json(res,403,{error:'forbidden'});if(req.method==='GET'){const file=u.searchParams.get('file')||'data.js';if(!validFile(file))return json(res,400,{error:'not_allowed'});return json(res,200,await gh.getContent(s.token,GITHUB_REPO_OWNER,GITHUB_REPO_NAME,file,GITHUB_BRANCH))}if(req.method==='PUT'){const b=await body(req);if(!validFile(b.file)||typeof b.content!=='string'||typeof b.sha!=='string')return json(res,400,{error:'invalid_payload'});try{return json(res,200,{ok:true,file:b.file,...await gh.putContent(s.token,GITHUB_REPO_OWNER,GITHUB_REPO_NAME,b.file,GITHUB_BRANCH,b.content,b.sha,s.login)})}catch(e){if(e.status===409||e.status===422)return json(res,409,{error:'conflict',message:e.message});throw e}}}
return json(res,404,{error:'not_found'})}catch(e){console.error(e);return json(res,e.status||500,{error:e.status===413?'body_too_large':'internal_error',message:prod?'Internal server error':e.message})}}
function start(){for(const k of['GITHUB_CLIENT_ID','GITHUB_CLIENT_SECRET','GITHUB_CALLBACK_URL','GITHUB_REPO_OWNER','GITHUB_REPO_NAME','SESSION_SECRET'])if(!process.env[k])throw new Error(`Missing ${k}`);return http.createServer(router).listen(Number(PORT),()=>console.log(`Hooxi API :${PORT}`))}
module.exports={router,start,_sessions:sessions};if(require.main===module)start();
