const test=require('node:test');
const assert=require('node:assert/strict');
const {handleRequest}=require('./index')._test;

const data={home:{appearance:{title:'Test'},cards:[],tracks:[]},archive:{mainline:[],stories:[],behindScenes:[],events:[]}};
function storage(initial=null){let value=initial;return{async get(){if(!value){const error=new Error('missing');error.code='NoSuchKey';throw error}return{content:Buffer.from(JSON.stringify(value))}},async put(key,body){assert.equal(key,'hooxi-zzz/site-data.json');value=JSON.parse(body.toString())},read:()=>value}}
function request(method,body,headers={}){return{method,path:'/site-data',headers,body:body?JSON.stringify(body):''}}
function body(response){return response.body?JSON.parse(response.body):null}

test('GET returns empty version before initialization',async()=>{const response=await handleRequest(request('GET'),{}, {storage:storage()});assert.equal(response.statusCode,200);assert.deepEqual(body(response),{version:0,updatedAt:null,data:null})});
test('PUT rejects wrong password',async()=>{process.env.EDIT_PASSWORD='secret';const response=await handleRequest(request('PUT',{expectedVersion:0,data},{'X-Edit-Password':'wrong'}),{}, {storage:storage()});assert.equal(response.statusCode,401)});
test('PUT saves valid data and increments version',async()=>{process.env.EDIT_PASSWORD='secret';const store=storage();const response=await handleRequest(request('PUT',{expectedVersion:0,data},{'X-Edit-Password':'secret'}),{}, {storage:store});assert.equal(response.statusCode,200);assert.equal(body(response).version,1);assert.equal(store.read().data.home.appearance.title,'Test')});
test('PUT prevents stale overwrite',async()=>{process.env.EDIT_PASSWORD='secret';const store=storage({version:2,updatedAt:'now',data});const response=await handleRequest(request('PUT',{expectedVersion:1,data},{'X-Edit-Password':'secret'}),{}, {storage:store});assert.equal(response.statusCode,409);assert.equal(body(response).version,2)});
test('PUT rejects invalid site document',async()=>{process.env.EDIT_PASSWORD='secret';const response=await handleRequest(request('PUT',{expectedVersion:0,data:{}},{'X-Edit-Password':'secret'}),{}, {storage:storage()});assert.equal(response.statusCode,400)});
test('two clients sync after save and stale client cannot overwrite',async()=>{process.env.EDIT_PASSWORD='secret';const store=storage();const clientA=body(await handleRequest(request('GET'),{}, {storage:store}));const clientB=body(await handleRequest(request('GET'),{}, {storage:store}));const changed=structuredClone(data);changed.home.appearance.title='Client A saved';const saved=await handleRequest(request('PUT',{expectedVersion:clientA.version,data:changed},{'X-Edit-Password':'secret'}),{}, {storage:store});assert.equal(saved.statusCode,200);const stale=await handleRequest(request('PUT',{expectedVersion:clientB.version,data},{'X-Edit-Password':'secret'}),{}, {storage:store});assert.equal(stale.statusCode,409);const refreshed=body(await handleRequest(request('GET'),{}, {storage:store}));assert.equal(refreshed.version,1);assert.equal(refreshed.data.home.appearance.title,'Client A saved')});
test('OPTIONS advertises password header',async()=>{const response=await handleRequest(request('OPTIONS'),{}, {storage:storage()});assert.equal(response.statusCode,204);assert.match(response.headers['Access-Control-Allow-Headers'],/X-Edit-Password/)});
